### ISSUE TITLE
Logra documentar el proyecto mediante el archivo readme.

### ISSUE THREAD

**Issue by waltercamino** [OrganizacionProyecto/Proyecto-TSDWAD#1]
Logra documentar el proyecto mediante el archivo readme.

**Comment by sinistri** [comment]
El objetivo principal de este documento es proporcionar una descripción completa y detallada del proyecto, dirigida a inspección por parte de profesores del ISPC, advirtiendo que el presente proyecto se trata de una tienda en línea especializada en la venta de productos naturales destinados al consumo. Contamos con un diseño integrado por clases que conectan tanto al administrador como al usuario con la base de datos para distintas finalidades ya sea de quien acceda. Entonces, el proyecto tiene como finalidad ofrecer a clientes, mediante una web, una plataforma intuitiva y segura para adquirir una amplia variedad de productos naturales, como alimentos orgánicos, suplementos dietéticos, productos de cuidado personal y más; y al administrador la seguridad en la recolección de datos.
