### ISSUE TITLE
El sistema de rutas (Routing) a fin de lograr la navegabilidad (no incluye rutas protegidas por el momento)

### ISSUE THREAD

**Issue by xNachooox2442** [OrganizacionProyecto/Proyecto-TSDWAD#10]

**Comment by waltercamino** [comment]
La implementación del sistema de rutas (Routing) para lograr la navegabilidad ha sido completada satisfactoriamente. A continuación, se detallan los puntos cumplidos:

Definición de rutas:

Se han definido todas las rutas necesarias para la navegación dentro de la aplicación.
Cada ruta mapea correctamente a sus respectivos componentes y vistas.
Configuración del router:

Se ha configurado el router principal para manejar las rutas definidas.
Se ha asegurado que la navegación entre rutas funcione de manera fluida y sin errores.
Navegación:

Se ha implementado la navegación básica entre las distintas secciones de la aplicación.
Los enlaces y botones de navegación funcionan correctamente, permitiendo a los usuarios moverse entre las diferentes páginas sin problemas.
Compatibilidad y pruebas:

Se han realizado pruebas para asegurar que todas las rutas sean accesibles y que la navegación sea coherente en diferentes navegadores y dispositivos.
Se ha verificado que la estructura de URLs sea clara y consistente.
Con esto, todas las tareas relacionadas con esta issue han sido completadas y verificadas. La funcionalidad de enrutamiento básico está operativa y funcionando según lo esperado, permitiendo una navegabilidad adecuada dentro de la aplicación.
