### ISSUE TITLE
(opcional) Proveer a los componentes datos  mediante servicios. 

### ISSUE THREAD

**Issue by xNachooox2442** [OrganizacionProyecto/Proyecto-TSDWAD#12]

**Comment by CeCogot** [comment]
Se tuvo que generar servicios para proveer de información a los componentes ya que sin ellos no podríamos haber avanzado en el proyecto:
- Se han implementado los servicios necesarios ( por ej. carrito, etc) para proveer datos a los componentes utilizados.
- Se realizaron pruebas que verifican el correcto funcionamiento de los componentes al recibir los datos.
