### ISSUE TITLE
La tienda deberá implementar mediante componentes lo referente a:

### ISSUE THREAD

**Issue by xNachooox2442** [OrganizacionProyecto/Proyecto-TSDWAD#14]
- [x] #19

- [x] #20

- [x] Galería de productos o servicios con posibilidad de acceder a la descripción de cada producto o servicio y a la compra.

- [x] #22

- [x] #21

- [x] #23

**Comment by CeCogot** [comment]
Hemos completado las tareas asignadas:

Landing page (página de aterrizaje) #19: Hemos finalizado la implementación de la Landing page, asegurándonos de que sea sencilla y de fácil funcionalidad para captar la atención de los visitantes.

Dashboard (panel de control) #20: El panel de control ha sido desarrollado con éxito, proporcionando una interfaz intuitiva para la gestión y el monitoreo de datos.

Galería de productos o servicios #21: La galería de productos y servicios está ahora disponible, permitiendo a los usuarios acceder a las descripciones detalladas y realizar compras de manera eficiente.

Quienes somos #22: Hemos completado la sección "Quienes somos", brindando información clara y concisa sobre nuestra empresa y equipo.

Contacto #23: La sección de contacto está operativa, facilitando la comunicación directa con los usuarios a través de formularios reactivos.

Gestión de usuarios #24: La funcionalidad de gestión de usuarios, incluyendo el login, registro y validaciones mediante formularios reactivos.
