### ISSUE TITLE
Conexion Frontend con Backend: Registro y Login

### ISSUE THREAD

**Issue by JoaquinCamino12** [OrganizacionProyecto/Proyecto-TSDWAD#35]
Conexión con el backend para el registro e inicio de sesión. Agregar rutas protegidas a la navegación en base al usuario autenticado/autorizado.

**Comment by waltercamino** [comment]
La implementación de la conexión con el backend para el registro e inicio de sesión, así como la protección de rutas basadas en la autenticación y autorización del usuario, ha sido completada satisfactoriamente. A continuación, se detallan los puntos cumplidos:

1. Conexión con el backend para el registro e inicio de sesión:
   - Se ha implementado el formulario de registro de usuario, permitiendo la creación de nuevos usuarios.
   - Se ha desarrollado el formulario de inicio de sesión, autenticando a los usuarios y almacenando el token recibido del backend.
   - La comunicación con el backend se ha establecido correctamente, manejando tanto respuestas exitosas como errores (validaciones, usuarios ya registrados, credenciales incorrectas, etc.).

2. Protección de rutas en la navegación:
   - Se han definido y protegido las rutas que requieren autenticación, impidiendo el acceso a usuarios no autenticados.
   - Se ha implementado la lógica de protección que verifica la autenticación del usuario antes de permitir el acceso a dichas rutas.
   - Los usuarios no autenticados son redirigidos adecuadamente a la página de inicio de sesión.
   - Se han implementado roles y permisos para acceder a rutas específicas, asegurando que solo usuarios autorizados puedan acceder a ciertos contenidos.
   - Los elementos de la interfaz de usuario se muestran u ocultan correctamente basándose en el estado de autenticación/autorización del usuario.

Con esto, todas las tareas relacionadas con esta issue han sido completadas y verificadas. La funcionalidad de registro e inicio de sesión, así como la protección de rutas, están operativas y funcionando según lo esperado.
