### ISSUE TITLE
Plantear Historias de Usuarios

### ISSUE THREAD

**Issue by AntonellaAc** [OrganizacionProyecto/Proyecto-TSDWAD#4]
Las historias de usuario representan funcionalidades o características del sistema desde la perspectiva del usuario. Para garantizar su claridad y utilidad, es importante redactarlas de manera adecuada, ya que deben ser descripciones cortas y simples de los requerimientos del proyecto.

**Comment by CeCogot** [comment]
Se generan las historias de usuario teniendo en cuenta 2 enfoques, cliente y vendedor ya que se trata de la pagina web de la tienda de productos Naturales Aymará, como vendedor requiere poder administrar el inventario, gestionar promociones, descuentos, etc., como clientes necesario que cumpla con búsqueda de productos, seguimiento de pedidos, realizar compras, contacto con el vendedor, reseñas,  etc.

**Comment by waltercamino** [comment]
Puntos de contacto con el cliente

Es fundamental entender las diferentes fases en las que nuestros prospectos y clientes interactúan con nuestra plataforma de comercio electrónico para crear historias de usuario que satisfagan sus necesidades en cada etapa del proceso.

Dado que nuestros visitantes de la fase de posicionamiento de la marca buscan información sobre quiénes somos y qué ofrecemos, podemos enfocarnos en historias de usuario que faciliten la exploración de nuestra oferta y generen asombro y aprecio por nuestros productos.

Para los visitantes en la fase de descubrimiento, donde están evaluando nuestros productos y servicios, es crucial proporcionar historias de usuario que destaquen la calidad y el valor de nuestra oferta, así como hacer que los precios, costos de envío y tiempos de envío sean fácilmente accesibles en línea.

En la fase de relacionamiento, donde nuestros visitantes están a punto de convertirse en clientes, debemos concentrarnos en historias de usuario que simplifiquen el proceso de compra, brindando opciones de autoservicio en línea las 24 horas del día, los 7 días de la semana, con costos de envío transparentes y un carrito de compras dinámico.

Finalmente, en la fase de retención, donde nuestros clientes desean realizar pedidos recurrentes y sentirse valorados, podemos desarrollar historias de usuario que ofrezcan descuentos automáticos a clientes leales, plantillas de pedidos personalizadas y acceso completo a la información de pedidos y facturas anteriores.

Al alinear nuestras historias de usuario con estas necesidades y expectativas, podemos mejorar significativamente la experiencia de nuestros clientes en todas las etapas del proceso de compra.
